## Estadistica Aplicada
Sesion 2 - 9 Agosto 

Bryan Alejandro Estrada Rodriguez 1844554

Una lista en python es una coleccion de objetos que puede ser de distintos tipos

In [2]:
alumno1 = ['Juan', 'Perez', 17]

In [3]:
type(alumno1)

list

In [4]:
alumno1

['Juan', 'Perez', 17]

In [5]:
estadistica_g4 = ['Dania', 'Karla', 'Alan', 'Vania']

In [6]:
estadistica_g4

['Dania', 'Karla', 'Alan', 'Vania']

In [8]:
estadistica_g4[2]

'Alan'

In [9]:
estadistica_g4[0]

'Dania'

In [12]:
estadistica_g4[0], estadistica_g4[2]

('Dania', 'Alan')

In [13]:
estadistica_g4[0:3]

['Dania', 'Karla', 'Alan']

In [20]:
yo_enFCFM =['Bryan','LA',7,80]

In [21]:
mi_promedio = yo_enFCFM[3]
mi_carrera = yo_enFCFM[1]


In [22]:
print(mi_carrera, mi_promedio)

LA 80


## Librerias/Modulos/Paquetes

Una libreria en python es un conjunto de codigos que le dice a python como determinas cosas

Una libreria primero se instala (única vez) y luego se le indica a python que la use

In [23]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [26]:
import yfinance as yf

yfinance.funcion(parametros) 
tambien se puede solo poner yf = yfinance

In [27]:
yf.download('APPL','2019-01-01','2020-12-31')

[*********************100%***********************]  1 of 1 completed


1 Failed download:
['APPL']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-01-01 -> 2020-12-31)')


,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,


## Numpy

Sirve para manejar numeros en python

In [29]:
import numpy as np

La estructura basica de numpy son los arreglos (arrays), que son una coleccion de objetos del mismo tipo (Numericos)

In [31]:
# crear la lista con las ventas de paletas
ventas = [12,23,34,45,56]

In [33]:
ventas = np.array(ventas)

In [36]:
type(ventas)

numpy.ndarray

In [37]:
# Promedio
np.mean(ventas)

34.0

In [39]:
# Suma
np.sum(ventas)

170

In [40]:
# Max
np.max(ventas)

56

In [41]:
# Min
np.min(ventas)

12

In [43]:
# Varianza Poblacional 
np.var(ventas)

242.0

In [44]:
# Varianza Muestral
np.var(ventas, ddof=1)

302.5

In [45]:
# Desviacion estandar poblacional
np.std(ventas)

15.556349186104045

In [47]:
# Desviacion muestral
np.std(ventas,ddof=1)

17.392527130926087

Vector

In [48]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [49]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [50]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [52]:
np.full(6,10)

array([10, 10, 10, 10, 10, 10])

In [60]:
# Semilla (Siempre mismos aleatorios)
np.random.seed(12)
aleatorios = np.random.randint(0,20,10)

In [61]:
aleatorios

array([11,  6, 17,  2,  3,  3, 12, 16, 17,  5])

In [64]:
aleatorios= np.sort(aleatorios)

In [65]:
aleatorios[[0,4]]

array([2, 6])

In [66]:
aleatorios[aleatorios > 10]

array([11, 12, 16, 17, 17])

In [67]:
aleatorios[aleatorios < 7]

array([2, 3, 3, 5, 6])

In [68]:
numeros = [1.2, 2.34, 5.18]

arreglo , 2 media, 3 redondear a 2 decimales

In [70]:
# funcion
round(np.mean(np.array(numeros)),2)

2.91

In [71]:
# Metodo
np.array(numeros).mean().round(2)

2.91